components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 2
        # [ИЗМЕНЕНО] добавлен task processor для kafka producer
        producer-task-processor:
            thread_name: producer
            worker_threads: 2
    default_task_processor: main-task-processor
    components:
        server:
            listener:
                port: 8082
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stdout'
                    level: info
        dynamic-config:
            defaults: {}
        testsuite-support: {}
        http-client:
        http-client-core:
            fs-task-processor: fs-task-processor
        dns-client:
            fs-task-processor: fs-task-processor
        items-storage: {}
        mongo-items:
            dbconnection: mongodb://mongo-db:27017/store_db
            dns_resolver: async
        
        items-cache:
            groups:
                - config_name: items-cache
                  db: items-cache
                  sharding_strategy: RedisStandalone 
            subscribe_groups: []    
            thread_pools:
                redis_thread_pool_size: 4
                sentinel_thread_pool_size: 1

        kafka-producer-items:
            delivery_timeout: 10s
            queue_buffering_max: 100ms
            enable_idempotence: true
            security_protocol: PLAINTEXT
 
        default-secdist-provider:
            config: configs/secdist.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        handler-get-items:
            path: /items
            method: GET
            task_processor: main-task-processor
        handler-get-item:
            path: /items/{id}
            method: GET
            task_processor: main-task-processor
        handler-create-item:
            path: /items
            method: POST
            task_processor: main-task-processor
        handler-update-item:
            path: /items/{id}
            method: PUT
            task_processor: main-task-processor
        handler-delete-item:
            path: /items/{id}
            method: DELETE
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
        tests-control:
            load-enabled: $testsuite-enabled
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
            throttling_enabled: false
