services:
  app:
    image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg-dev:v2.14
    volumes:
      - ..:/home/user/myservice:cached
    # УБРАТЬ network_mode: service:db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    depends_on:
      - db
      - mongo-db
    environment:
      - DB_HOST=db
      - DB_NAME=store_db
      - DB_USER=user
      - DB_PASS=pass
    networks:
      - store-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=store_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../postgresql/schemas:/docker-entrypoint-initdb.d:ro
    networks:
      - store-network
  mongo-db:
    image: mongo:5.0
    container_name: mongo-store
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=store_db
    volumes:
      - ../mongo:/docker-entrypoint-initdb.d:ro
    networks:           
      - store-network
      
volumes:
  db-data:

networks:
  store-network:
    driver: bridge