components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 2
    default_task_processor: main-task-processor
    components:
        server:
            listener:
                port: 8083
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stdout'
                    level: info
        dynamic-config:
            defaults: {}
        testsuite-support: {}
        http-client:
        http-client-core:
            fs-task-processor: fs-task-processor
        dns-client:
            fs-task-processor: fs-task-processor
        cart-storage: {}
        postgres-db:
            dbconnection: postgresql://user:pass@db:5432/store_db
            blocking_task_processor: fs-task-processor
            dns_resolver: async
        handler-get-cart:
            path: /cart
            method: GET
            task_processor: main-task-processor
        handler-add-to-cart:
            path: /cart
            method: POST
            task_processor: main-task-processor
            # item-service-url: $item-service-url
            item-service-url: "http://localhost:8082"
        handler-remove-from-cart:
            path: /cart/{item_id}
            method: DELETE
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
        tests-control:
            load-enabled: $testsuite-enabled
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
            throttling_enabled: false

config_vars: configs/config_vars.yaml
